//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_scp_net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public feature()
        {
            this.scps = new HashSet<scp>();
        }
    
        public int id { get; set; }
        public int scp_id { get; set; }
        public string short_description { get; set; }
        public string full_description { get; set; }
        public string color { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scp> scps { get; set; }
    }
}
