//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_scp_net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interviews
    {
        public int id { get; set; }
        public Nullable<int> scp_id { get; set; }
        public System.DateTime interview_date { get; set; }
        public string transcription { get; set; }
    
        public virtual scp scp { get; set; }
    }
}
