//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_scp_net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class scp_databaseEntities : DbContext
    {
        public scp_databaseEntities()
            : base("name=scp_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<feature> features { get; set; }
        public virtual DbSet<scp> scps { get; set; }
        public virtual DbSet<scp_skills> scp_skills { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
