//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_scp_net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scp
    {
        public int id { get; set; }
        public string name { get; set; }
        public string scp_link { get; set; }
        public string feeling { get; set; }
        public string picture { get; set; }
        public int class_id { get; set; }
        public int type_id { get; set; }
        public int feature_id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual feature feature { get; set; }
        public virtual type type { get; set; }
    }
}
