//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_scp_net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scp_skills
    {
        public int id { get; set; }
        public int scp_id { get; set; }
        public int skll_id { get; set; }
    
        public virtual scp scp { get; set; }
        public virtual skills skills { get; set; }
    }
}
