//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_scp_net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCPEntities : DbContext
    {
        public SCPEntities()
            : base("name=SCPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classes> classes { get; set; }
        public virtual DbSet<features> features { get; set; }
        public virtual DbSet<interviews> interviews { get; set; }
        public virtual DbSet<scp> scp { get; set; }
        public virtual DbSet<scp_enemies> scp_enemies { get; set; }
        public virtual DbSet<scp_skills> scp_skills { get; set; }
        public virtual DbSet<skills> skills { get; set; }
        public virtual DbSet<types> types { get; set; }
    }
}
